# Generated by Django 6.0.6 on 2026-06-18 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='descriptin',
            new_name='descripton',
        ),
    ]
