# Generated by Django 6.0.6 on 2026-07-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='Badge',
        ),
        migrations.AddField(
            model_name='tour',
            name='badge',
            field=models.CharField(blank=True, choices=[('featured', 'ویژه'), ('popular', 'محبوب'), ('economy', 'اقتصادی')], null=True),
        ),
    ]
