# Generated by Django 6.0.6 on 2026-06-19 12:31

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_rename_descriptin_tour_descripton'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='tour_type',
            field=models.CharField(blank=True, choices=[('internal', 'داخلی'), ('external', 'خارجی')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='end_date',
            field=django_jalali.db.models.jDateField(),
        ),
        migrations.AlterField(
            model_name='tour',
            name='start_date',
            field=django_jalali.db.models.jDateField(),
        ),
    ]
