# Generated by Django 6.0.6 on 2026-07-10 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_remove_tour_badge_tour_badge'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSerction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.URLField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='tour',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='title',
        ),
        migrations.AddField(
            model_name='tour',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
