# Generated by Django 6.0.6 on 2026-07-10 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_heroserction_remove_tour_end_date_remove_tour_slug_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HeroSerction',
            new_name='HeroSection',
        ),
    ]
