# Generated by Django 6.0.6 on 2026-06-21 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_tourimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourimage',
            old_name='Tour',
            new_name='tour',
        ),
    ]
