# Generated by Django 6.0.6 on 2026-07-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_rename_heroserction_herosection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='tour_type',
            field=models.CharField(blank=True, choices=[('internal', 'داخلی'), ('external', 'خارجی'), ('one_day', 'یک روزه'), ('icognito', 'ناشناس')], max_length=10, null=True),
        ),
    ]
