# Generated by Django 6.0.6 on 2026-06-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_rename_tour_tourimage_tour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='descripton',
            new_name='description',
        ),
        migrations.AddField(
            model_name='location',
            name='is_search',
            field=models.BooleanField(default=True),
        ),
    ]
