# Generated by Django 6.0.6 on 2026-07-18 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_alter_tour_tour_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.URLField(max_length=500)),
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tours.city')),
            ],
        ),
    ]
