# Generated by Django 6.0.6 on 2026-06-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_rename_descripton_tour_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='is_search',
        ),
        migrations.AddField(
            model_name='location',
            name='is_destination',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='is_origin',
            field=models.BooleanField(default=False),
        ),
    ]
