# Generated by Django 6.0.6 on 2026-07-18 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_populardestination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='populardestination',
            name='city',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='popular_destination', to='tours.city'),
        ),
    ]
