# Generated by Django 6.0.6 on 2026-06-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_remove_location_is_search_location_is_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='hotel_stars',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
