# Generated by Django 6.0.6 on 2026-07-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_alter_populardestination_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
