# Generated by Django 6.0.6 on 2026-06-23 20:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_tour_hotel_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='hotel_stars',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
