# Generated by Django 6.0.6 on 2026-07-22 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0009_category_remove_tour_tour_type_tour_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='herosection',
            old_name='images',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='tourimage',
            old_name='images',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='tour',
            name='badge',
            field=models.CharField(blank=True, choices=[('featured', 'ویژه'), ('popular', 'محبوب'), ('economy', 'اقتصادی')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tours.category'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_tours', to='tours.city'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_tours', to='tours.city'),
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.tour')),
            ],
        ),
    ]
