# Generated by Django 6.0.6 on 2026-06-28 20:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0009_alter_tour_hotel_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='cover',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='cover'),
        ),
        migrations.AlterField(
            model_name='tourimage',
            name='images',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='images'),
        ),
    ]
