# Generated by Django 6.0.6 on 2026-07-22 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0011_alter_tour_destination_alter_tour_origin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='populardestination',
            old_name='images',
            new_name='image',
        ),
    ]
