# Generated by Django 6.0.6 on 2026-07-23 09:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0013_itinerary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelimage',
            name='tour',
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to='tours.tour'),
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=250)),
                ('stars', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.country')),
            ],
        ),
        migrations.AddField(
            model_name='hotelimage',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tours.hotel'),
        ),
        migrations.AddField(
            model_name='tour',
            name='hotel',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.hotel'),
        ),
        migrations.CreateModel(
            name='HotelFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='tours.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='HotelFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='tours.hotel')),
            ],
        ),
    ]
