# Generated by Django 6.0.6 on 2026-07-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0015_alter_hotelimage_image_alter_tour_hotel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='meals',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
